apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-twitter
  namespace: loki-twitter
spec:
  selector:
    matchLabels:
      app: loki-twitter
  replicas: 1
  template:
    metadata:
      labels:
        app: loki-twitter
    spec:
      containers:
        - name: loki-twitter
          image: techgnosis/loki-twitter:2
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TWITTER_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loki-twitter
                  key: twitter_bearer_token
            - name: LOKI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: loki-twitter
                  key: loki_username
            - name: LOKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loki-twitter
                  key: loki_password
            - name: LOKI_URL
              valueFrom:
                secretKeyRef:
                  name: loki-twitter
                  key: loki_url
            
